### ISSUE TITLE
K线图无法查看

### ISSUE THREAD

**Issue by JammyR** [bytebeats/mns#111]
更新到最新版之后，双击打开K线图，会显示一个空白的Tab，没有任何显示，只有上面的分时图，日线，周线的切换，但是切换了也是空白的，有同样情况的吗

**Comment by bytebeats** [comment]
你的网络情况怎么样？这些图片都是实时获取的，网络慢的时候可能有些耗时

**Comment by JammyR** [comment]
网络都是正常的，双击之后等了1-2分钟都不会出图

**Comment by bytebeats** [comment]
我研究复现一下

**Comment by JammyR** [comment]
我更新到有K线版本后，就没加载出来过K线，也有可能是我电脑问题，想看看有没人一样的情况

**Comment by bytebeats** [comment]
有日志信息打印出来没有? 在 Event Window

**Comment by bytebeats** [comment]
选中之后右击有反应吗? 右击也有入口.

**Comment by JammyR** [comment]
右键有反应，event窗口有图片下载地址，复制出来是能打开的，但是IDEA里面是没有图片的
![微信图片_20211103085355](https://user-images.githubusercontent.com/15321501/139971307-185c4229-8c7c-46e8-9999-391f3428aac2.png)

**Comment by JammyR** [comment]
经测试，是由于我版本过低(19.3)才导致不能显示图片的，升级到最新版可以了，谢谢！

**Comment by bytebeats** [comment]
以为支持 2 年内的 IDEA 就可以了, 但还是有更低版本的的存在...
