### ISSUE TITLE
请问环境是jdk11吗

### ISSUE THREAD

**Issue by quanmin8888** [bytebeats/mns#122]
我这边一直报错 
类文件具有错误的版本 55.0, 应为 52.0
请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by bytebeats** [comment]
你需要保证 IDE SDK 跟你依赖中所使用的 SDK 版本保持一致.

**Comment by quanmin8888** [comment]
您好！您的邮件我已收到！我会尽快看的，谢谢

**Comment by bytebeats** [comment]
通过 `File` -> `Project Structure`,  查看 `Project Settings` -> `Project`, 确保  `SDK` & `Language Level` 选择 `Intellij IDEA Community Edition IC xxx` 和 `8`, 之后  `Module`下面的 `mns`及选项 `main`和`test`中的 `Sources` -> `Language Level` 和 `Dependencies` -> `Module SDK` 选中 `Project SDK`.

**Comment by quanmin8888** [comment]
> 
我的是jdk8的
