### ISSUE TITLE
Crypotos 刷不出数据

### ISSUE THREAD

**Issue by skrlst** [bytebeats/mns#136]
大佬，Crypotos 出问题了，东西拉不出来，别的好像都还可以用

![image](https://github.com/bytebeats/mns/assets/70947084/4d3da869-8e44-41cf-ae7f-62c473b79bc1)

**Comment by skrlst** [comment]
配置是这样的

![image](https://github.com/bytebeats/mns/assets/70947084/a71ff175-5063-436c-a1fe-51bc462dc715)

**Comment by mcc7178** [comment]
me too

**Comment by mcc7178** [comment]
可以上google x ,插件的Crypotos 不显示

**Comment by skrlst** [comment]
> me too 我也是



后来我换了接口：https://data-api.binance.vision/api/v3/ticker/price

文档：https://binance-docs.github.io/apidocs/spot/en/#symbol-price-ticker

![image](https://github.com/bytebeats/mns/assets/70947084/0629a3bf-39e8-4cbf-9b94-9431dfc7e7e6)

**Comment by skrlst** [comment]
[libs.zip](https://github.com/bytebeats/mns/files/14913208/libs.zip)

如果需要，可以试试这个，它是本地打包的插件，用这个仓库改的。

![image](https://github.com/bytebeats/mns/assets/70947084/2c6ea29f-33a9-4d93-8fea-81994b10c328)
