### ISSUE TITLE
在安装时出现了版本异常。

### ISSUE THREAD

**Issue by manBoooooooooooooom** [bytebeats/mns#17]
![image](https://user-images.githubusercontent.com/59555513/89376999-81385000-d723-11ea-84d0-7e66206bfc9e.png)

**Comment by bytebeats** [comment]
idea 无法下载 2020.1.4 版本的 intellij platform plugin 的 sdk.
现在最新代码应该是 2020.2 版本的, 更新一下代码.
如果你的 idea 还是无法下载这个 sdk 的话, 请将上图中的链接在浏览器中打开下载并配置.
如果浏览器中也无法下载的话, 那就真的只能怪网络了...
我的idea 本身下载这个 sdk 也比较吃力, 但是浏览器中则下载的很快. 如果都不能下载的话, 那真的只能白瞎了...
@manBoooooooooooooom

**Comment by manBoooooooooooooom** [comment]
安装完成了。
自己通过浏览器下载了这个SDK，然后根据下面这个网站完成了配置
https://www.jb51.net/article/186034.htm
但是简介模式不生效 我也不知道是不是我安装的有问题。
最后感谢大佬分享 以后可以一边流眼泪一边写代码了

**Comment by bytebeats** [comment]
简洁模式还不成熟, 所以还没有上传; 隐秘模式, 想要将里面的汉字变成拼音防止被人偷窃到也是 work in progress. :-)
边流泪边敲代码 👍

**Comment by manBoooooooooooooom** [comment]
期待大佬后续版本 哈哈哈哈
