### ISSUE TITLE
安装后操作界面在哪里？

### ISSUE THREAD

**Issue by DavidWhom** [bytebeats/mns#18]
![image](https://user-images.githubusercontent.com/30634936/90383328-919ce300-e0b2-11ea-8498-220b0c90da04.png)

![image](https://user-images.githubusercontent.com/30634936/90383564-e4769a80-e0b2-11ea-8b34-cf9c129b2d42.png)

如图，设置里面已经有mns，但是主界面找不到mns的入口。

已star

**Comment by bytebeats** [comment]
<img width="26" alt="WX20200817-175800@2x" src="https://user-images.githubusercontent.com/4122407/90383834-47683180-e0b3-11ea-8f5a-2ae338052de5.png">
已经有了, 年骚.
