### ISSUE TITLE
录入的股票代码会莫名其妙自动消失

### ISSUE THREAD

**Issue by DavidWhom** [bytebeats/mns#25]
![image](https://user-images.githubusercontent.com/30634936/91271839-62226080-e7ad-11ea-9887-739c79393f10.png)

**Comment by DavidWhom** [comment]
前几天用得好好地，但是今天所有的代码莫名被清掉了。idea有卡顿退出过

**Comment by bytebeats** [comment]
@DavidWhom 版本是多少? 现在最新版本应该是 1.5.1
这个问题也挺奇怪的...我也是第一次遇到 :-(

**Comment by DavidWhom** [comment]
直接在idea下载的，也是1.51
![image](https://user-images.githubusercontent.com/30634936/91424706-bb14f600-e88c-11ea-98a8-2092be4061fb.png)

idea版本是2020的
![image](https://user-images.githubusercontent.com/30634936/91424770-d253e380-e88c-11ea-89fb-f0fb15ac69a1.png)

**Comment by bytebeats** [comment]
@DavidWhom 在插件出现问题的时候, 是否 ide 本身出现了什么问题? 比如, 本身打开的项目没有能够正确打开? 或者没有 indicing 完成? 或者其它的什么情况?

**Comment by DavidWhom** [comment]
那倒没注意，后续有再出现再注意一下现象。
给个建议，红框圈起来的是否可以考虑做个可选的隐藏功能，或者展示拼音即可。

![image](https://user-images.githubusercontent.com/30634936/91509915-23f08280-e90e-11ea-81a7-6feea371db49.png)

**Comment by bytebeats** [comment]
@DavidWhom 这个功能加入 to-do list. 以及, 简洁模式还没有激活, 也在写 :-)
