### ISSUE TITLE
设置界面乱码

### ISSUE THREAD

**Issue by deng81416754** [bytebeats/mns#27]
![0284f7ee022dd7d1179660b78556c25](https://user-images.githubusercontent.com/16043435/91680084-be55fd80-eb7c-11ea-9bc3-25964c220469.png)

**Comment by bytebeats** [comment]
@deng81416754 是的, 乱码的问题已经解决. 新版本正在市场审核中...

**Comment by deng81416754** [comment]
android stuido 1.5.2版本目前还搜索不到。等待你的新版
