### ISSUE TITLE
丰富股票的指标

### ISSUE THREAD

**Issue by DavidWhom** [bytebeats/mns#30]
- 显示买12345、卖12345的挂单数
- 显示主力的净流入
- 显示成交的最低和最高价格

http://hq.sinajs.cn/list=sh601899 这个接口有买卖12345数据以及最低和最高价格。没仔细看repo主用的接口有没有。
主力净流入可能还得找找

**Comment by bytebeats** [comment]
@DavidWhom 已经写在 todo 里面了, 我正在考虑 UI 怎么展示及交互, 以及顺便优化一下现在的窗口.

**Comment by DavidWhom** [comment]
肯定要有个股票详情界面，不然这么多参数显示在表格里容易看花眼

**Comment by bytebeats** [comment]
@DavidWhom 1.6.0添加了股票详情, 已提交市场审核, please stay tuned.

**Comment by DavidWhom** [comment]
很强大佬，这个项目必火。详情页面这么大，买卖12345感觉都可以都显示出来，便于看哪个价位在压单

**Comment by bytebeats** [comment]
@DavidWhom 有买卖五档的数据, 写 UI 的时候发现没位置放了 :-)

**Comment by DavidWhom** [comment]
![image](https://user-images.githubusercontent.com/30634936/93316871-51f72180-f83f-11ea-80e9-f9f142f3726d.png)
竖向加4行，左边买，右边卖。感觉还行
