### ISSUE TITLE
bug 点不出来了

### ISSUE THREAD

**Issue by yzjjdcf** [bytebeats/mns#39]
闪一下就 没了

**Comment by bytebeats** [comment]
@yzjjdcf 点哪了? 是不是你的 IDEA 正在indicesing? 
在 IDEA 建立索引的过程中, 窗口是不展示的

**Comment by yzjjdcf** [comment]
这我还真没注意，就是点mns，窗口闪一下就没了，然后我ide清理缓存，重装才好的。应该不是indicesing中，我配置很快的。。。

**Comment by bytebeats** [comment]
IDEA 版本?

**Comment by yzjjdcf** [comment]
![image](https://user-images.githubusercontent.com/13599694/94113461-7d9a8d00-fe79-11ea-8b9a-09fb7673bb05.png)
当时我是点的 切换window 是window还是float那几个选项，然后突然窗口就没了，右键点击mns，上面所有的选项就都选不了了

**Comment by bytebeats** [comment]
@yzjjdcf  我觉着是你误点了 `Remove From Sidebar`...
可以尝试从 View -> Tool Window 或者 Window -> Active Tool Window 里面选中恢复.

**Comment by yzjjdcf** [comment]
可能吧 好像是？记不清了。可以留意一下
