### ISSUE TITLE
对于现在 UI和 UE, 看看大家有什么好的意见跟建议.

### ISSUE THREAD

**Issue by bytebeats** [bytebeats/mns#55]
如题.
1, 对于窗口, 大家是比较喜欢放在左右两侧的竖直结构, 还是放在底部的横向结构.
2, 对于股票详情页, 现在内容有些拥挤, 大家有没有什么好的想法.
3, K 线图大家想放在哪展示.

请见到的 mns 用户, 可以发表一下看法, 我参考一下, 对于以后新功能的添加以及重构, 添柴加火.

**Comment by yejiahao** [comment]
vscode 上面的股票插件有鼠标悬停浮窗效果，这个效果觉得还挺好，希望后续有实现

**Comment by MicroCountry** [comment]
1.窗口，现在还好，因为idea支持 dock  unpinned 模式，这样在哪显示都一样，看的时候点一下
2.股票详情可以参考同花顺的手机详情页，同花顺就是这种键值对，其实这些信息不是很重要，因为这个可以其他时间看，上班更关注实时信息
3.K线图和分时图，可以考虑在单击某个股票悬浮出来，可以考虑东方财富web端，点击查看股票的分时图，会弹出一个悬浮框，上面有几个tab栏，一个分时图，几个级别的K线图，加上均线

希望添加的功能
1.可以在展示页面上手动增加股票，比如增加个添加按钮，可以搜索中文，然后添加进去。股票代码很不友好啊。
2.可以点击悬浮查看分时，以及K线图，最好还要显示各级别均线
3.提醒功能，可以为单个股票设置预警价格

如果人手不够，愿意加入

**Comment by bytebeats** [comment]
@MicroCountry K 线图的接口有了, 但是是jsonp 格式的, 不是很好解析 :-); 搜索的接口我有机会在网页上面 inpect 一下, 看看好不好解析, 好不好用.

**Comment by bytebeats** [comment]
@yejiahao VS Code 上面有一个插件可以查看详情, 提供的内容挺好的, 但是是 web 版本的. 有时间去参考一下它的源码.
