### ISSUE TITLE
只能查找基金？

### ISSUE THREAD

**Issue by MackHuang** [bytebeats/mns#62]

**Comment by bytebeats** [comment]
可以添加跟删除, 不过前者使用体验不太好, 还没找着时间优化一下; 后者则是还没有放开, 同样也是交互不好的问题.
我找个时间看一下吧.

**Comment by MackHuang** [comment]
好的，非常感谢



在 2021-01-08 17:52:56，"Chen Pan" <notifications@github.com> 写道：

可以添加跟删除, 不过前者使用体验不太好, 还没找着时间优化一下; 后者则是还没有放开, 同样也是交互不好的问题.
我找个时间看一下吧.

**Comment by bytebeats** [comment]
基金的搜索, 添加, 删除已经在 1.8.0 版本开放.
