### ISSUE TITLE
本地打包加载的时候报错找不到Pinyin类

### ISSUE THREAD

**Issue by ziningmei** [bytebeats/mns#63]

**Comment by ziningmei** [comment]
本地打包到磁盘上，从磁盘安装插件，重启报错

**Comment by bytebeats** [comment]
你需要先设置一个 Build Artifacts 任务. 
![image](https://user-images.githubusercontent.com/4122407/104267571-d8a9cb80-54cc-11eb-8697-71157b5b98e2.png)

然后 执行 Build -> Build Artifacts -> Build/Rebuild. 如果生成了 out/artifacts/mns_main_jar/mns.main.jar文件, 再执行./gradlew build就可以在 lib 文件夹下面看到了 mns-x.x.x.jar文件了.

**Comment by ziningmei** [comment]
感谢感谢，可以了，麻烦大佬帮我删一下这个issue，我用错账号了
