### ISSUE TITLE
经常性卡死

### ISSUE THREAD

**Issue by huskyui** [bytebeats/mns#64]
### 现象
经常在点
![image](https://user-images.githubusercontent.com/23629016/104539275-256ddd80-5658-11eb-869e-4dcad05ae985.png)
－号时，卡死

**Comment by bytebeats** [comment]
这个 "-"号属于 IDE 系统的 API, 插件做不了什么.
点击卡顿的情况可能跟你 IDE 正在做的事情多有关系.
我 IDE 在 building 或者 indexing 阶段插件显示内容也会不可用.
@huskyui

**Comment by huskyui** [comment]
好的
