### ISSUE TITLE
为什么就白酒的基金显示不了，其他三个基金都显示了

### ISSUE THREAD

**Issue by QSHCUPID** [bytebeats/mns#65]
![image](https://user-images.githubusercontent.com/30258253/109094262-a12d7080-7754-11eb-9222-b6799bc00c5d.png)

**Comment by sun830910** [comment]
看是会有个error

**Comment by QSHCUPID** [comment]
白酒表示受到了歧视，哈哈

**Comment by QSHCUPID** [comment]
还有基金不能自动刷新，只能自己手动点同步

**Comment by sun830910** [comment]
![截圖 2021-02-25 上午10 36 54](https://user-images.githubusercontent.com/33343137/109094836-99ba9700-7755-11eb-9cff-130b0bf46600.png)

**Comment by sun830910** [comment]
> 还有基金不能自动刷新，只能自己手动点同步

可以自动刷新的吧？我这边看是可以的

**Comment by QSHCUPID** [comment]
> > 还有基金不能自动刷新，只能自己手动点同步
> 
> 可以自动刷新的吧？我这边看是可以的

哦哦，可能是加了白酒，导致不能自动刷新，去掉了白酒就可以自动刷新了

**Comment by QSHCUPID** [comment]
上面的报错，是接口返回的json解析错误吗，小白一个

**Comment by bytebeats** [comment]
@QSHCUPID @sun830910 在使用正则表达式里的零宽断言进行匹配时, 招商白酒的这个基金返回的名字里"招商中证白酒指数(LOF)"包含了小括号, 这个小括号影响了正规匹配, 这是个 bug, 我找时间处理一下.

**Comment by bytebeats** [comment]
@QSHCUPID @sun830910 在接口返回结果有 bug 时把循环给停了, 所以没有继续刷新.

**Comment by bytebeats** [comment]
@QSHCUPID @sun830910 已经修复提交了市场等待审核, 明后天就可以更新了. 先 Close 掉这个 issue 了.

**Comment by QSHCUPID** [comment]
666，牛逼，逼得我去学了下零宽断言
