### ISSUE TITLE
添加基金不显示，且更新时出现以下信息

### ISSUE THREAD

**Issue by yanyi5496** [bytebeats/mns#66]
stops updating 天天基金 data because of com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 44 path $.name

**Comment by bytebeats** [comment]
Duplicate of #65

**Comment by bytebeats** [comment]
@yanyi5496 添加的是哪个基金?

**Comment by yanyi5496** [comment]
> @yanyi5496 添加的是哪个基金?

160222

**Comment by bytebeats** [comment]
等明后天审核通过后更新一下吧.
