### ISSUE TITLE
A股数量展示不正确

### ISSUE THREAD

**Issue by wangxingzhen** [bytebeats/mns#69]
一个小问题，

![image](https://user-images.githubusercontent.com/44692411/109476651-1af58f00-7ab2-11eb-947b-16a81239824e.png)

你看我这里设置了三个A股代码，但是不知为何，总是展示四个股票

![image](https://user-images.githubusercontent.com/44692411/109476572-0913ec00-7ab2-11eb-9d47-d8b576d83fdc.png)

**Comment by bytebeats** [comment]
@wangxingzhen 
确定在`设置`里面输入这些内容之后, 点击`确定`,` 窗口`里面点击`同步`之后展示的是这些?
现在有些问题都摸不着头脑了...

**Comment by wangxingzhen** [comment]
是的，确定，而且我昨天设置了多次，并且设置完成之后，还尝试重启我的编辑器，还是没用，后来重启电脑才解决

**Comment by bytebeats** [comment]
@wangxingzhen 你的环境是什么 IDE? 什么版本?

**Comment by wangxingzhen** [comment]
> @wangxingzhen 你的环境是什么 IDE? 什么版本?

我在两个ide上都试过了，都不好使，后来重启才发现好使了，两个IDE分别是 phpstorm和goland，都是最新版

**Comment by bytebeats** [comment]
@wangxingzhen 我用 Phpstorm 复现这个问题了, 我想一下是怎么回事, 怎么解决.
