### ISSUE TITLE
找不到哪里可以设置

### ISSUE THREAD

**Issue by duxingxia081** [bytebeats/mns#70]
找不到哪里可以设置，设置的地方在哪里啊，就第一次加了几只股票，后续找不到设置的地方了

**Comment by duxingxia081** [comment]
![image](https://user-images.githubusercontent.com/11461954/109907713-d4847800-7cdd-11eb-9e77-5e03eb459913.png)

**Comment by bytebeats** [comment]
`Intellij IDEA` -> `Preferences` -> `Other Settings` -> `Money Never Sleeps`
